In [11]:
import pandas as pd
import datetime as dt

In [12]:
df= pd.read_csv('Resources/WeatherEvents_Jan2016-Dec2020.csv', infer_datetime_format=True, parse_dates= ['StartTime(UTC)','EndTime(UTC)'])
df.head()

,EventId,Type,Severity,StartTime(UTC),EndTime(UTC),TimeZone,AirportCode,LocationLat,LocationLng,City,County,State,ZipCode
0,W-1,Snow,Light,2016-01-06 23:14:00,2016-01-07 00:34:00,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0
1,W-2,Snow,Light,2016-01-07 04:14:00,2016-01-07 04:54:00,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0
2,W-3,Snow,Light,2016-01-07 05:54:00,2016-01-07 15:34:00,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0
3,W-4,Snow,Light,2016-01-08 05:34:00,2016-01-08 05:54:00,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0
4,W-5,Snow,Light,2016-01-08 13:54:00,2016-01-08 15:54:00,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0

In [3]:
#df.dtypes

EventId                   object
Type                      object
Severity                  object
StartTime(UTC)    datetime64[ns]
EndTime(UTC)      datetime64[ns]
TimeZone                  object
AirportCode               object
LocationLat              float64
LocationLng              float64
City                      object
County                    object
State                     object
ZipCode                  float64
dtype: object

In [10]:
#df['StartTime(UTC)'] = pd.to_datetime(df['Date'])

In [13]:
#creating the Duration column 

df['Duration'] = (df['EndTime(UTC)'] - df['StartTime(UTC)']).dt.seconds
df.head()

,EventId,Type,Severity,StartTime(UTC),EndTime(UTC),TimeZone,AirportCode,LocationLat,LocationLng,City,County,State,ZipCode,Duration
0,W-1,Snow,Light,2016-01-06 23:14:00,2016-01-07 00:34:00,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0,4800
1,W-2,Snow,Light,2016-01-07 04:14:00,2016-01-07 04:54:00,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0,2400
2,W-3,Snow,Light,2016-01-07 05:54:00,2016-01-07 15:34:00,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0,34800
3,W-4,Snow,Light,2016-01-08 05:34:00,2016-01-08 05:54:00,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0,1200
4,W-5,Snow,Light,2016-01-08 13:54:00,2016-01-08 15:54:00,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0,7200

In [14]:
#converting the duration column into minutes 
df['Duration']= df['Duration'] / 60
df

,EventId,Type,Severity,StartTime(UTC),EndTime(UTC),TimeZone,AirportCode,LocationLat,LocationLng,City,County,State,ZipCode,Duration
0,W-1,Snow,Light,2016-01-06 23:14:00,2016-01-07 00:34:00,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0,80.0
1,W-2,Snow,Light,2016-01-07 04:14:00,2016-01-07 04:54:00,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0,40.0
2,W-3,Snow,Light,2016-01-07 05:54:00,2016-01-07 15:34:00,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0,580.0
3,W-4,Snow,Light,2016-01-08 05:34:00,2016-01-08 05:54:00,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0,20.0
4,W-5,Snow,Light,2016-01-08 13:54:00,2016-01-08 15:54:00,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0,120.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6274201,W-6276144,Snow,Light,2020-12-14 17:30:00,2020-12-15 01:53:00,US/Mountain,KBVR,42.5833,-108.2833,Lander,Fremont,WY,82520.0,503.0
6274202,W-6276145,Snow,Moderate,2020-12-15 01:53:00,2020-12-15 03:19:00,US/Mountain,KBVR,42.5833,-108.2833,Lander,Fremont,WY,82520.0,86.0
6274203,W-6276146,Snow,Light,2020-12-15 03:19:00,2020-12-15 05:53:00,US/Mountain,KBVR,42.5833,-108.2833,Lander,Fremont,WY,82520.0,154.0
6274204,W-6276147,Snow,Light,2020-12-23 04:24:00,2020-12-23 05:53:00,US/Mountain,KBVR,42.5833,-108.2833,Lander,Fremont,WY,82520.0,89.0
6274205,W-6276148,Snow,Light,2020-12-23 10:53:00,2020-12-23 11:26:00,US/Mountain,KBVR,42.5833,-108.2833,Lander,Fremont,WY,82520.0,33.0

In [15]:
df = df.drop(columns= ['ZipCode', 'AirportCode', 'County' ])
df.head()

,EventId,Type,Severity,StartTime(UTC),EndTime(UTC),TimeZone,LocationLat,LocationLng,City,State,Duration
0,W-1,Snow,Light,2016-01-06 23:14:00,2016-01-07 00:34:00,US/Mountain,38.0972,-106.1689,Saguache,CO,80.0
1,W-2,Snow,Light,2016-01-07 04:14:00,2016-01-07 04:54:00,US/Mountain,38.0972,-106.1689,Saguache,CO,40.0
2,W-3,Snow,Light,2016-01-07 05:54:00,2016-01-07 15:34:00,US/Mountain,38.0972,-106.1689,Saguache,CO,580.0
3,W-4,Snow,Light,2016-01-08 05:34:00,2016-01-08 05:54:00,US/Mountain,38.0972,-106.1689,Saguache,CO,20.0
4,W-5,Snow,Light,2016-01-08 13:54:00,2016-01-08 15:54:00,US/Mountain,38.0972,-106.1689,Saguache,CO,120.0

In [16]:
dict = {"EventId" :"eventid",
        "Type":"type",
        "Severity":"severity",
        "StartTime(UTC)": "startTime",
        "EndTime(UTC)":"endTime",
        "TimeZone": "timeZone",
        "LocationLat": "lat",
        "LocationLng": "lng",
        "City":"city",
        "State": "state",
        "Duration": "duration"          
                
        
       }
  
# call rename () method
df.rename(columns=dict,
          inplace=True)
  
# print Data frame after rename columns
df

,eventid,type,severity,startTime,endTime,timeZone,lat,lng,city,state,duration
0,W-1,Snow,Light,2016-01-06 23:14:00,2016-01-07 00:34:00,US/Mountain,38.0972,-106.1689,Saguache,CO,80.0
1,W-2,Snow,Light,2016-01-07 04:14:00,2016-01-07 04:54:00,US/Mountain,38.0972,-106.1689,Saguache,CO,40.0
2,W-3,Snow,Light,2016-01-07 05:54:00,2016-01-07 15:34:00,US/Mountain,38.0972,-106.1689,Saguache,CO,580.0
3,W-4,Snow,Light,2016-01-08 05:34:00,2016-01-08 05:54:00,US/Mountain,38.0972,-106.1689,Saguache,CO,20.0
4,W-5,Snow,Light,2016-01-08 13:54:00,2016-01-08 15:54:00,US/Mountain,38.0972,-106.1689,Saguache,CO,120.0
...,...,...,...,...,...,...,...,...,...,...,...
6274201,W-6276144,Snow,Light,2020-12-14 17:30:00,2020-12-15 01:53:00,US/Mountain,42.5833,-108.2833,Lander,WY,503.0
6274202,W-6276145,Snow,Moderate,2020-12-15 01:53:00,2020-12-15 03:19:00,US/Mountain,42.5833,-108.2833,Lander,WY,86.0
6274203,W-6276146,Snow,Light,2020-12-15 03:19:00,2020-12-15 05:53:00,US/Mountain,42.5833,-108.2833,Lander,WY,154.0
6274204,W-6276147,Snow,Light,2020-12-23 04:24:00,2020-12-23 05:53:00,US/Mountain,42.5833,-108.2833,Lander,WY,89.0
6274205,W-6276148,Snow,Light,2020-12-23 10:53:00,2020-12-23 11:26:00,US/Mountain,42.5833,-108.2833,Lander,WY,33.0

In [15]:
# grouped_type = df.groupby(["Type"]).count()
# grouped_type.head()

In [16]:
# grouped_type = df.groupby(["type", 'city']).count()['eventid']
# grouped_type

type   city
Cold   Abbeville                   27
       Aberdeen                   991
       Aberdeen Proving Ground     99
       Abilene                     80
       Abingdon                    10
                                 ...
Storm  York                        58
       Yukon                       30
       Yuma                         2
       Zephyrhills                  2
       Zionsville                   3
Name: eventid, Length: 9847, dtype: int64

In [17]:
# df.City.unique()

AttributeError: 'DataFrame' object has no attribute 'City'

In [17]:
#selecting the cities 
new_df = df.loc[df['state'].isin(['NY', 'CA', 'IL', 'TX', 'AZ','PA'])]
new_df = new_df.loc[new_df['city'].isin(['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas','Austin'])]
new_df['year'] = pd.DatetimeIndex(new_df['startTime']).year
new_df

,eventid,type,severity,startTime,endTime,timeZone,lat,lng,city,state,duration,year
727176,W-727376,Cold,Severe,2016-01-08 16:51:00,2016-01-08 17:51:00,US/Eastern,40.7790,-73.9692,New York,NY,60.0,2016
727177,W-727377,Cold,Severe,2016-01-09 15:51:00,2016-01-09 16:26:00,US/Eastern,40.7790,-73.9692,New York,NY,35.0,2016
727178,W-727378,Rain,Light,2016-01-09 17:51:00,2016-01-09 18:51:00,US/Eastern,40.7790,-73.9692,New York,NY,60.0,2016
727179,W-727379,Rain,Light,2016-01-10 07:51:00,2016-01-10 09:39:00,US/Eastern,40.7790,-73.9692,New York,NY,108.0,2016
727180,W-727380,Rain,Moderate,2016-01-10 09:39:00,2016-01-10 10:02:00,US/Eastern,40.7790,-73.9692,New York,NY,23.0,2016
...,...,...,...,...,...,...,...,...,...,...,...,...
5856606,W-5858406,Precipitation,UNK,2020-12-31 17:44:00,2020-12-31 18:01:00,US/Central,29.9844,-95.3607,Houston,TX,17.0,2020
5856607,W-5858407,Rain,Moderate,2020-12-31 18:15:00,2020-12-31 19:53:00,US/Central,29.9844,-95.3607,Houston,TX,98.0,2020
5856608,W-5858408,Rain,Light,2020-12-31 19:53:00,2020-12-31 20:37:00,US/Central,29.9844,-95.3607,Houston,TX,44.0,2020
5856609,W-5858409,Rain,Moderate,2020-12-31 20:37:00,2020-12-31 21:53:00,US/Central,29.9844,-95.3607,Houston,TX,76.0,2020
5856610,W-5858410,Rain,Light,2020-12-31 23:22:00,2020-12-31 23:53:00,US/Central,29.9844,-95.3607,Houston,TX,31.0,2020

In [38]:
stat_df = round(new_df.groupby(['year','city','type']).sum()['duration'] / 1440, 1)
stat_df.head()

stat_df = pd.DataFrame(stat_df)

stat_df = stat_df.reset_index()
stat_df['avg_perc_year'] = round(stat_df['duration'] / 365 * 100, 1)
stat_df

     year         city           type  duration  avg_perc_year
0    2016       Austin           Cold       0.3            0.1
1    2016       Austin            Fog      10.6            2.9
2    2016       Austin           Hail       0.0            0.0
3    2016       Austin  Precipitation       0.1            0.0
4    2016       Austin           Rain      40.9           11.2
..    ...          ...            ...       ...            ...
278  2020  San Antonio          Storm       0.0            0.0
279  2020    San Diego           Cold       1.4            0.4
280  2020    San Diego            Fog      70.7           19.4
281  2020    San Diego  Precipitation       0.1            0.0
282  2020    San Diego           Rain      38.2           10.5

[283 rows x 5 columns]

In [39]:
city = list(stat_df['city'])
lat = []
lng = []

for i in range(len(city)):
    if str(city[i]) == "New York":
        lat.append(40.713)
        lng.append(-74.01)
    elif str(city[i]) == "Los Angeles":
        lat.append(34.05)
        lng.append(-118.24)
    elif str(city[i]) == "Chicago":
        lat.append(41.88)
        lng.append(-87.63)
    elif str(city[i]) == "Houston":
        lat.append(29.76)
        lng.append(-95.37)
    elif str(city[i]) == "Philadelphia":
        lat.append(39.95)
        lng.append(-75.17)
    elif str(city[i]) == "Phoenix":
        lat.append(33.45)
        lng.append(-112.07)
    elif str(city[i]) == "San Antonio":
        lat.append(29.42)
        lng.append(-98.49)
    elif str(city[i]) == "San Diego":
        lat.append(32.72)
        lng.append(-117.16)
    elif str(city[i]) == "Dallas":
        lat.append(32.78)
        lng.append(-96.80)
    elif str(city[i]) == "Austin":
        lat.append(30.27)
        lng.append(-97.74)   
        
stat_df['lat'] = lat
stat_df['lng'] = lng

stat_df

     year         city           type  duration  avg_perc_year    lat     lng
0    2016       Austin           Cold       0.3            0.1  30.27  -97.74
1    2016       Austin            Fog      10.6            2.9  30.27  -97.74
2    2016       Austin           Hail       0.0            0.0  30.27  -97.74
3    2016       Austin  Precipitation       0.1            0.0  30.27  -97.74
4    2016       Austin           Rain      40.9           11.2  30.27  -97.74
..    ...          ...            ...       ...            ...    ...     ...
278  2020  San Antonio          Storm       0.0            0.0  29.42  -98.49
279  2020    San Diego           Cold       1.4            0.4  32.72 -117.16
280  2020    San Diego            Fog      70.7           19.4  32.72 -117.16
281  2020    San Diego  Precipitation       0.1            0.0  32.72 -117.16
282  2020    San Diego           Rain      38.2           10.5  32.72 -117.16

[283 rows x 7 columns]

In [ ]:
#checking for unique event IDs
# [f"{x}: {new_df[x].nunique()}" for x in new_df.columns]

In [27]:
#dependency to connect with sql alchelmy 
from sqlalchemy import create_engine

In [41]:
#connecting
engine = create_engine('postgresql://postgres:postgres@localhost:5432/weather_db')
connection = engine.connect()

In [42]:
#making sure of the connection!
engine.table_names()

['weatherhist', 'summaryview']

In [30]:
#changing the columns to lower case
new_df.columns= new_df.columns.str.lower()
new_df.head()

,eventid,type,severity,starttime,endtime,timezone,lat,lng,city,state,duration,year
727176,W-727376,Cold,Severe,2016-01-08 16:51:00,2016-01-08 17:51:00,US/Eastern,40.779,-73.9692,New York,NY,60.0,2016
727177,W-727377,Cold,Severe,2016-01-09 15:51:00,2016-01-09 16:26:00,US/Eastern,40.779,-73.9692,New York,NY,35.0,2016
727178,W-727378,Rain,Light,2016-01-09 17:51:00,2016-01-09 18:51:00,US/Eastern,40.779,-73.9692,New York,NY,60.0,2016
727179,W-727379,Rain,Light,2016-01-10 07:51:00,2016-01-10 09:39:00,US/Eastern,40.779,-73.9692,New York,NY,108.0,2016
727180,W-727380,Rain,Moderate,2016-01-10 09:39:00,2016-01-10 10:02:00,US/Eastern,40.779,-73.9692,New York,NY,23.0,2016

In [43]:

stat_df.columns= stat_df.columns.str.lower()
stat_df.head()

   year    city           type  duration  avg_perc_year    lat    lng
0  2016  Austin           Cold       0.3            0.1  30.27 -97.74
1  2016  Austin            Fog      10.6            2.9  30.27 -97.74
2  2016  Austin           Hail       0.0            0.0  30.27 -97.74
3  2016  Austin  Precipitation       0.1            0.0  30.27 -97.74
4  2016  Austin           Rain      40.9           11.2  30.27 -97.74

In [35]:
new_df.to_sql(name='weatherhist', con=engine, if_exists='append', index=False)

In [ ]:
#exporting the dataset into a csv file
# new_df.to_csv('Resources/weather.csv', index=False)

In [46]:
stat_df.to_sql(name='summaryview', con=engine, if_exists='append', index=False)